title: "Priyaranjan Pattnayak"
email: "[your-email@example.com]"
description: >-
  Senior Principal Data Scientist at Oracle Cloud. Specializing in NLP, Generative AI, and AI for enterprise.
baseurl: ""
# Force all traffic to primary domain
url: "https://priyanpattnayak.com"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
author:
  name   : "Priyaranjan Pattnayak"
  avatar : "https://bpb-us-e1.wpmucdn.com/sites.uw.edu/dist/a/194/files/2025/08/PriyanHeadshot.jpeg"
  bio    : "AI/ML researcher at Oracle Cloud working on Generative AI and NLP at scale."
  location : "Seattle, WA"
  links:
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=gXWbDuUAAAAJ"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/priyaranjanpattnayak"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ppattnayak"
    - label: "Oracle Blog"
      icon: "fas fa-blog"
      url: "https://blogs.oracle.com/authors/priyan-pattnayak"
